name: "diskinfo monitor"
version: "0.0.1"
slug: "diskinfo"
description: "sync disk temperature and health state, based on smartctl"
url: "https://github.com/xswxm/hassio-addons/tree/main/diskinfo"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
options:
  broker: "192.168.123.200"
  port: "1883"
  username: "mqtt"
  password: "mqtt"
  interval: 3600
schema:
  broker: str
  port: str
  username: str
  password: str
  interval: int
