name: "Zhonghong VRF"
version: "0.1.1"
slug: "zhonghong_vrf"
description: "HTTP based Zhonghong vrf controller"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
options:
  broker: "192.168.123.200"
  port: "1883"
  username: "mqtt"
  password: "mqtt"
  gateway: "192.168.123.251"
schema:
  broker: str
  port: str
  username: str
  password: str
  gateway: str
